# Generated by Django 4.2 on 2023-04-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('cant_entradas', models.IntegerField()),
                ('hijos_participantes', models.CharField(max_length=2)),
            ],
        ),
    ]
