# Generated by Django 4.2 on 2023-04-30 19:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='opinion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
