# Generated by Django 4.2 on 2023-05-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_alter_cliente_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
